unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded!"

set -g mouse on

set -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on

set -g prefix C-s

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Move status bar to the top
set-option -g status-position top

bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
# bind c new-window -c "#{pane_current_path}"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rose-pine/tmux' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

# Enable all status bar components
set -g @rose_pine_host 'off'       # Show hostname
set -g @rose_pine_user 'off'       # Show username
set -g @rose_pine_directory 'off'  # Show current directory
set -g @rose_pine_date_time '' # Show date & time (customize format)
set -g @rose_pine_show_current_program 'on' # Show active program in window name
set -g @rose_pine_show_pane_directory 'off'  # Show directory in window name

# Ensure status bar background is visible
set -g @rose_pine_bar_bg_disable 'on' # Enable background color
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# Ensure all window-related information is visible
set -g @rose_pine_only_windows 'off' # Show all modules, not just windows
set -g @rose_pine_disable_active_window_menu 'on' # Keep active window menu
set -g @rose_pine_default_window_behavior 'on' # Allow rose-pine's custom window list

# Customize separators for a visually appealing status bar
set -g @rose_pine_right_separator ' <- ' 
set -g @rose_pine_left_separator ' -> ' 

# Customize icons for better visibility
set -g @rose_pine_session_icon '' 
set -g @rose_pine_current_window_icon '' 
set -g @rose_pine_folder_icon '' 
set -g @rose_pine_username_icon '' 
set -g @rose_pine_hostname_icon '󰒋' 
set -g @rose_pine_date_time_icon '󰃰' 
set -g @rose_pine_window_status_separator "  " 

run '~/.tmux/plugins/tpm/tpm'
